export type Product = {
    id: number,
    urlId: string,
    name: string,
    description: string,
    price: number,
    imageUrl: string,
    category: string,
    inStock: boolean,
    stock: number,
    tags: string,
    rating: number,
    // Additional fields
    discountPercentage?: number,
    salePrice?: number,
    brand?: string,
    manufacturer?: string,
    weight?: number,
    dimensions?: {
        length: number,
        width: number,
        height: number,
        unit: string,
    },
    color?: string | string[],
    size?: string | string[],
    createdAt?: Date | string,
    updatedAt?: Date | string,
    isPublished?: boolean,
    isFeatured?: boolean,
    relatedProducts?: number[], // IDs of related products
    reviews?: Array<{
        userId: number,
        userName: string,
        rating: number,
        comment: string,
        date: Date | string,
    }>,
    sku?: string, // Stock Keeping Unit
    barcode?: string, // UPC/EAN/ISBN
    shippingInfo?: {
        weight: number,
        dimensions: {
            length: number,
            width: number, 
            height: number,
        },
        freeShipping: boolean,
        shippingCost: number,
    },
    taxInfo?: {
        taxable: boolean,
        taxCategory: string,
        taxRate?: number,
    },
    variations?: Array<{
        id: number,
        attributes: Record<string, string>, // e.g., {color: "red", size: "XL"}
        price: number,
        stock: number,
        imageUrl?: string,
    }>,
};

export const products: Product[] = [
    {
        id: 1,
        urlId: "product-1",
        name: "Product 1",
        description: "Description of Product 1",
        price: 29.99,
        imageUrl: "/images/product-1.jpg",
        category: "Electronics",
        inStock: true,
        stock: 100,
        tags: "tag1, tag2",
        rating: 4.5,
    },
    {
        id: 2,
        urlId: "product-2",
        name: "Product 2",
        description: "Description of Product 2",
        price: 49.99,
        imageUrl: "/images/product-2.jpg",
        category: "Clothing",
        inStock: false,
        stock: 0,
        tags: "tag3, tag4",
        rating: 3.8,
    },
    {
        id: 3,
        urlId: "product-3",
        name: "Product 3",
        description: "Description of Product 3",
        price: 19.99,
        imageUrl: "/images/product-3.jpg",
        category: "Books",
        inStock: true,
        stock: 50,
        tags: "tag5, tag6",
        rating: 4.0,
    },
    {
        id: 4,
        urlId: "product-4",
        name: "Product 4",
        description: "Description of Product 4",
        price: 99.99,
        imageUrl: "/images/product-4.jpg",
        category: "Home & Kitchen",
        inStock: true,
        stock: 20,
        tags: "tag7, tag8",
        rating: 5.0,
    },
    {
        id: 5,
        urlId: "product-5",
        name: "Product 5",
        description: "Description of Product 5",
        price: 39.99,
        imageUrl: "/images/product-5.jpg",
        category: "Sports & Outdoors",
        inStock: true,
        stock: 75,
        tags: "tag9, tag10",
        rating: 4.2,
    },
    {
        id: 6,
        urlId: "product-6",
        name: "Product 6",
        description: "Description of Product 6",
        price: 59.99,
        imageUrl: "/images/product-6.jpg",
        category: "Toys & Games",
        inStock: false,
        stock: 0,
        tags: "tag11, tag12",
        rating: 3.5,
    },
    {
        id: 7,
        urlId: "product-7",
        name: "Product 7",
        description: "Description of Product 7",
        price: 89.99,
        imageUrl: "/images/product-7.jpg",
        category: "Beauty & Personal Care",
        inStock: true,
        stock: 30,
        tags: "tag13, tag14",
        rating: 4.8,
    },
    {
        id: 8,
        urlId: "product-8",
        name: "Product 8",
        description: "Description of Product 8",
        price: 24.99,
        imageUrl: "/images/product-8.jpg",
        category: "Automotive",
        inStock: true,
        stock: 60,
        tags: "tag15, tag16",
        rating: 4.1,
    },
    {
        id: 9,
        urlId: "product-9",
        name: "Product 9",
        description: "Description of Product 9",
        price: 74.99,
        imageUrl: "/images/product-9.jpg",
        category: "Health & Wellness",
        inStock: true,
        stock: 40,
        tags: "tag17, tag18",
        rating: 4.6,
    },
    {
        id: 10,
        urlId: "product-10",
        name: "Product 10",
        description: "Description of Product 10",
        price: 14.99,
        imageUrl: "/images/product-10.jpg",
        category: "Office Supplies",
        inStock: false,
        stock: 0,
        tags: "tag19, tag20",
        rating: 3.9,
    },
];